- name: List members of SYS1.PARMLIB
  hosts: zoslab
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"

  tasks:
  - name: Execute TSO command List Dataset (LISTDSD) and allow for maximum return code of 4.
  zos_tso_command:
    commands:
      - LISTDSD DATASET('SYS1.PARMLIB') ALL GENERIC
    max_rc: 4
    register: result

- name: Display result
  debug:
    msg: "{{ result }}"