---

- name: List active started tasks
  hosts: zoslab
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"

   

  tasks:
    

    - name: Query all active jobs
      zos_job_query:
      register: active_jobs

    - name: Keep only started tasks
      set_fact:
        started_tasks: >-
          {{
            active_jobs.jobs
            | selectattr('job_class', 'defined')
            | selectattr('job_class', 'equalto', 'STC')
            | list
          }}

    - name: Display result
      debug:
        msg: "{{ started_tasks | map(attribute='job_name') | list }}" 
         