- name: List members of SYS.PARMLIB
  hosts: zoslab
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"

  tasks:

    - name: List members in "{{ pds }}"
      zos_tso_command:
        commands:
          - "LISTDS '{{ pds }}' MEMBERS"
      register: result

    - name: Display result
      debug:
        msg: "{{ result }}"